let a = 20;
let b = 30;

try {
    console.log('a + c =', a + c)
} catch(err) {
    console.log('Error here :', err)
}